# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bos/v1/actions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x62os/v1/actions.proto\x12\x0e\x62raiins.bos.v1"\x0e\n\x0cStartRequest"(\n\rStartResponse\x12\x17\n\x0f\x61lready_running\x18\x01 \x01(\x08"\x10\n\x0eRestartRequest"*\n\x0fRestartResponse\x12\x17\n\x0f\x61lready_running\x18\x01 \x01(\x08"\x0f\n\rRebootRequest"\x10\n\x0eRebootResponse"\r\n\x0bStopRequest"\'\n\x0cStopResponse\x12\x17\n\x0f\x61lready_stopped\x18\x01 \x01(\x08"\x14\n\x12PauseMiningRequest"-\n\x13PauseMiningResponse\x12\x16\n\x0e\x61lready_paused\x18\x01 \x01(\x08"\x15\n\x13ResumeMiningRequest".\n\x14ResumeMiningResponse\x12\x16\n\x0e\x61lready_mining\x18\x01 \x01(\x08".\n\x1cSetLocateDeviceStatusRequest\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08"-\n\x1aLocateDeviceStatusResponse\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08"\x1e\n\x1cGetLocateDeviceStatusRequest2\xc7\x05\n\x0e\x41\x63tionsService\x12\x44\n\x05Start\x12\x1c.braiins.bos.v1.StartRequest\x1a\x1d.braiins.bos.v1.StartResponse\x12\x41\n\x04Stop\x12\x1b.braiins.bos.v1.StopRequest\x1a\x1c.braiins.bos.v1.StopResponse\x12V\n\x0bPauseMining\x12".braiins.bos.v1.PauseMiningRequest\x1a#.braiins.bos.v1.PauseMiningResponse\x12Y\n\x0cResumeMining\x12#.braiins.bos.v1.ResumeMiningRequest\x1a$.braiins.bos.v1.ResumeMiningResponse\x12J\n\x07Restart\x12\x1e.braiins.bos.v1.RestartRequest\x1a\x1f.braiins.bos.v1.RestartResponse\x12G\n\x06Reboot\x12\x1d.braiins.bos.v1.RebootRequest\x1a\x1e.braiins.bos.v1.RebootResponse\x12q\n\x15SetLocateDeviceStatus\x12,.braiins.bos.v1.SetLocateDeviceStatusRequest\x1a*.braiins.bos.v1.LocateDeviceStatusResponse\x12q\n\x15GetLocateDeviceStatus\x12,.braiins.bos.v1.GetLocateDeviceStatusRequest\x1a*.braiins.bos.v1.LocateDeviceStatusResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "bos.v1.actions_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_STARTREQUEST"]._serialized_start = 40
    _globals["_STARTREQUEST"]._serialized_end = 54
    _globals["_STARTRESPONSE"]._serialized_start = 56
    _globals["_STARTRESPONSE"]._serialized_end = 96
    _globals["_RESTARTREQUEST"]._serialized_start = 98
    _globals["_RESTARTREQUEST"]._serialized_end = 114
    _globals["_RESTARTRESPONSE"]._serialized_start = 116
    _globals["_RESTARTRESPONSE"]._serialized_end = 158
    _globals["_REBOOTREQUEST"]._serialized_start = 160
    _globals["_REBOOTREQUEST"]._serialized_end = 175
    _globals["_REBOOTRESPONSE"]._serialized_start = 177
    _globals["_REBOOTRESPONSE"]._serialized_end = 193
    _globals["_STOPREQUEST"]._serialized_start = 195
    _globals["_STOPREQUEST"]._serialized_end = 208
    _globals["_STOPRESPONSE"]._serialized_start = 210
    _globals["_STOPRESPONSE"]._serialized_end = 249
    _globals["_PAUSEMININGREQUEST"]._serialized_start = 251
    _globals["_PAUSEMININGREQUEST"]._serialized_end = 271
    _globals["_PAUSEMININGRESPONSE"]._serialized_start = 273
    _globals["_PAUSEMININGRESPONSE"]._serialized_end = 318
    _globals["_RESUMEMININGREQUEST"]._serialized_start = 320
    _globals["_RESUMEMININGREQUEST"]._serialized_end = 341
    _globals["_RESUMEMININGRESPONSE"]._serialized_start = 343
    _globals["_RESUMEMININGRESPONSE"]._serialized_end = 389
    _globals["_SETLOCATEDEVICESTATUSREQUEST"]._serialized_start = 391
    _globals["_SETLOCATEDEVICESTATUSREQUEST"]._serialized_end = 437
    _globals["_LOCATEDEVICESTATUSRESPONSE"]._serialized_start = 439
    _globals["_LOCATEDEVICESTATUSRESPONSE"]._serialized_end = 484
    _globals["_GETLOCATEDEVICESTATUSREQUEST"]._serialized_start = 486
    _globals["_GETLOCATEDEVICESTATUSREQUEST"]._serialized_end = 516
    _globals["_ACTIONSSERVICE"]._serialized_start = 519
    _globals["_ACTIONSSERVICE"]._serialized_end = 1230
# @@protoc_insertion_point(module_scope)
