# -*- coding: utf-8 -*-

# ------------------------------------------------------------------------------
#  Copyright 2022 Upstream Data Inc                                            -
#                                                                              -
#  Licensed under the Apache License, Version 2.0 (the "License");             -
#  you may not use this file except in compliance with the License.            -
#  You may obtain a copy of the License at                                     -
#                                                                              -
#      http://www.apache.org/licenses/LICENSE-2.0                              -
#                                                                              -
#  Unless required by applicable law or agreed to in writing, software         -
#  distributed under the License is distributed on an "AS IS" BASIS,           -
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    -
#  See the License for the specific language governing permissions and         -
#  limitations under the License.                                              -
# ------------------------------------------------------------------------------

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bos/v1/units.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x62os/v1/units.proto\x12\x0e\x62raiins.bos.v1"+\n\x0cMegaHashrate\x12\x1b\n\x13megahash_per_second\x18\x01 \x01(\x01"+\n\x0cGigaHashrate\x12\x1b\n\x13gigahash_per_second\x18\x01 \x01(\x01"+\n\x0cTeraHashrate\x12\x1b\n\x13terahash_per_second\x18\x01 \x01(\x01"\x1a\n\tFrequency\x12\r\n\x05hertz\x18\x01 \x01(\x01"\x17\n\x07Voltage\x12\x0c\n\x04volt\x18\x01 \x01(\x01"\x15\n\x05Power\x12\x0c\n\x04watt\x18\x01 \x01(\x04"-\n\x0fPowerEfficiency\x12\x1a\n\x12joule_per_terahash\x18\x01 \x01(\x01"\x1f\n\x0bTemperature\x12\x10\n\x08\x64\x65gree_c\x18\x01 \x01(\x01"\x1a\n\x0b\x42\x61sesPoints\x12\x0b\n\x03\x62sp\x18\x01 \x01(\r"\x16\n\x05Hours\x12\r\n\x05hours\x18\x01 \x01(\rb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "bos.v1.units_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_MEGAHASHRATE"]._serialized_start = 38
    _globals["_MEGAHASHRATE"]._serialized_end = 81
    _globals["_GIGAHASHRATE"]._serialized_start = 83
    _globals["_GIGAHASHRATE"]._serialized_end = 126
    _globals["_TERAHASHRATE"]._serialized_start = 128
    _globals["_TERAHASHRATE"]._serialized_end = 171
    _globals["_FREQUENCY"]._serialized_start = 173
    _globals["_FREQUENCY"]._serialized_end = 199
    _globals["_VOLTAGE"]._serialized_start = 201
    _globals["_VOLTAGE"]._serialized_end = 224
    _globals["_POWER"]._serialized_start = 226
    _globals["_POWER"]._serialized_end = 247
    _globals["_POWEREFFICIENCY"]._serialized_start = 249
    _globals["_POWEREFFICIENCY"]._serialized_end = 294
    _globals["_TEMPERATURE"]._serialized_start = 296
    _globals["_TEMPERATURE"]._serialized_end = 327
    _globals["_BASESPOINTS"]._serialized_start = 329
    _globals["_BASESPOINTS"]._serialized_end = 355
    _globals["_HOURS"]._serialized_start = 357
    _globals["_HOURS"]._serialized_end = 379
# @@protoc_insertion_point(module_scope)
